// flow-typed signature: 3813ce6381882cee26e4d617475762a8
// flow-typed version: <<STUB>>/copy-webpack-plugin_v^0.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-webpack-plugin/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-webpack-plugin/index' {
  declare module.exports: $Exports<'copy-webpack-plugin'>;
}
declare module 'copy-webpack-plugin/index.js' {
  declare module.exports: $Exports<'copy-webpack-plugin'>;
}
declare module 'copy-webpack-plugin/test/index.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/test/index'>;
}
