// flow-typed signature: bb56dcd23263f5efebfe7645a6ab87f5
// flow-typed version: <<STUB>>/flow-watch_v^1.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-watch/src/flow-watch' {
  declare module.exports: any;
}

declare module 'flow-watch/src/runFlow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-watch/src/flow-watch.js' {
  declare module.exports: $Exports<'flow-watch/src/flow-watch'>;
}
declare module 'flow-watch/src/runFlow.js' {
  declare module.exports: $Exports<'flow-watch/src/runFlow'>;
}
