// flow-typed signature: e698cc84a86b8468b1c429608ba8d1a7
// flow-typed version: <<STUB>>/imagine-engine_v^0.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagine-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagine-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imagine-engine/lib/imagine' {
  declare module.exports: any;
}

declare module 'imagine-engine/lib/jquery-1.11.0' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/component/collider' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/component/element' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/component/FPS' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/imagine' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/imagine/input' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/imagine/input/mouse' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/imagine/object' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/imagine/time' {
  declare module.exports: any;
}

declare module 'imagine-engine/src/imagine/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imagine-engine/lib/imagine.js' {
  declare module.exports: $Exports<'imagine-engine/lib/imagine'>;
}
declare module 'imagine-engine/lib/jquery-1.11.0.js' {
  declare module.exports: $Exports<'imagine-engine/lib/jquery-1.11.0'>;
}
declare module 'imagine-engine/src/component/collider.js' {
  declare module.exports: $Exports<'imagine-engine/src/component/collider'>;
}
declare module 'imagine-engine/src/component/element.js' {
  declare module.exports: $Exports<'imagine-engine/src/component/element'>;
}
declare module 'imagine-engine/src/component/FPS.js' {
  declare module.exports: $Exports<'imagine-engine/src/component/FPS'>;
}
declare module 'imagine-engine/src/imagine.js' {
  declare module.exports: $Exports<'imagine-engine/src/imagine'>;
}
declare module 'imagine-engine/src/imagine/input.js' {
  declare module.exports: $Exports<'imagine-engine/src/imagine/input'>;
}
declare module 'imagine-engine/src/imagine/input/mouse.js' {
  declare module.exports: $Exports<'imagine-engine/src/imagine/input/mouse'>;
}
declare module 'imagine-engine/src/imagine/object.js' {
  declare module.exports: $Exports<'imagine-engine/src/imagine/object'>;
}
declare module 'imagine-engine/src/imagine/time.js' {
  declare module.exports: $Exports<'imagine-engine/src/imagine/time'>;
}
declare module 'imagine-engine/src/imagine/utils.js' {
  declare module.exports: $Exports<'imagine-engine/src/imagine/utils'>;
}
