// flow-typed signature: e9564658011d183004e9d17b49c8333d
// flow-typed version: <<STUB>>/img-element-loader_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'img-element-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'img-element-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'img-element-loader/index' {
  declare module.exports: $Exports<'img-element-loader'>;
}
declare module 'img-element-loader/index.js' {
  declare module.exports: $Exports<'img-element-loader'>;
}
