// flow-typed signature: 8b857811b5e7e73e06cf6e4fa0b49dda
// flow-typed version: <<STUB>>/javascript-astar_v^0.4.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-astar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'javascript-astar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'javascript-astar/astar' {
  declare module.exports: any;
}

declare module 'javascript-astar/demo/demo' {
  declare module.exports: any;
}

declare module 'javascript-astar/demo/jquery-1.7.1.min' {
  declare module.exports: any;
}

declare module 'javascript-astar/Gruntfile' {
  declare module.exports: any;
}

declare module 'javascript-astar/test/qunit' {
  declare module.exports: any;
}

declare module 'javascript-astar/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'javascript-astar/astar.js' {
  declare module.exports: $Exports<'javascript-astar/astar'>;
}
declare module 'javascript-astar/demo/demo.js' {
  declare module.exports: $Exports<'javascript-astar/demo/demo'>;
}
declare module 'javascript-astar/demo/jquery-1.7.1.min.js' {
  declare module.exports: $Exports<'javascript-astar/demo/jquery-1.7.1.min'>;
}
declare module 'javascript-astar/Gruntfile.js' {
  declare module.exports: $Exports<'javascript-astar/Gruntfile'>;
}
declare module 'javascript-astar/test/qunit.js' {
  declare module.exports: $Exports<'javascript-astar/test/qunit'>;
}
declare module 'javascript-astar/test/tests.js' {
  declare module.exports: $Exports<'javascript-astar/test/tests'>;
}
