// flow-typed signature: eb2cf7b5277fddc61f570dc75b8aa25c
// flow-typed version: <<STUB>>/karma-firefox-launcher_v~0.1.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-firefox-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-firefox-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-firefox-launcher/index' {
  declare module.exports: $Exports<'karma-firefox-launcher'>;
}
declare module 'karma-firefox-launcher/index.js' {
  declare module.exports: $Exports<'karma-firefox-launcher'>;
}
