// flow-typed signature: ab359257596ae6d504a7da8bd21464f8
// flow-typed version: <<STUB>>/karma-growl-reporter_v^0.1.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-growl-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-growl-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-growl-reporter/index' {
  declare module.exports: $Exports<'karma-growl-reporter'>;
}
declare module 'karma-growl-reporter/index.js' {
  declare module.exports: $Exports<'karma-growl-reporter'>;
}
