// flow-typed signature: 42af4822d6e6ab1c260e226aeeed8fd1
// flow-typed version: <<STUB>>/karma-nyan-reporter_v0.0.60/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-nyan-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-nyan-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-nyan-reporter/lib/data_types' {
  declare module.exports: any;
}

declare module 'karma-nyan-reporter/lib/printers' {
  declare module.exports: any;
}

declare module 'karma-nyan-reporter/lib/shell_util' {
  declare module.exports: any;
}

declare module 'karma-nyan-reporter/lib/storage_util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-nyan-reporter/index' {
  declare module.exports: $Exports<'karma-nyan-reporter'>;
}
declare module 'karma-nyan-reporter/index.js' {
  declare module.exports: $Exports<'karma-nyan-reporter'>;
}
declare module 'karma-nyan-reporter/lib/data_types.js' {
  declare module.exports: $Exports<'karma-nyan-reporter/lib/data_types'>;
}
declare module 'karma-nyan-reporter/lib/printers.js' {
  declare module.exports: $Exports<'karma-nyan-reporter/lib/printers'>;
}
declare module 'karma-nyan-reporter/lib/shell_util.js' {
  declare module.exports: $Exports<'karma-nyan-reporter/lib/shell_util'>;
}
declare module 'karma-nyan-reporter/lib/storage_util.js' {
  declare module.exports: $Exports<'karma-nyan-reporter/lib/storage_util'>;
}
