// flow-typed signature: 3c4dff7398c0a46da8b2101a00a4d801
// flow-typed version: <<STUB>>/karma-html-reporter_v^0.2.6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-html-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-html-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-html-reporter/index' {
  declare module.exports: $Exports<'karma-html-reporter'>;
}
declare module 'karma-html-reporter/index.js' {
  declare module.exports: $Exports<'karma-html-reporter'>;
}
