// flow-typed signature: 3801ed0effb27ab2c866d3337a83d94c
// flow-typed version: <<STUB>>/karma-chrome-launcher_v^0.1.8/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-chrome-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-chrome-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-chrome-launcher/test/jsflags.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-chrome-launcher/index' {
  declare module.exports: $Exports<'karma-chrome-launcher'>;
}
declare module 'karma-chrome-launcher/index.js' {
  declare module.exports: $Exports<'karma-chrome-launcher'>;
}
declare module 'karma-chrome-launcher/test/jsflags.spec.js' {
  declare module.exports: $Exports<'karma-chrome-launcher/test/jsflags.spec'>;
}
