export default {  
   "grid":{  
      "7_0":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "8_0":{  
         "type":"GREYWALLCORNER2",
         "rotation":0
      },
      "9_0":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "10_0":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "11_0":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "12_0":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "13_0":{  
         "type":"GREYWALLCORNER2",
         "rotation":0
      },
      "14_0":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "7_1":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_1":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_1":{  
         "type":"TILES2",
         "rotation":0
      },
      "10_1":{  
         "type":"TILES2",
         "rotation":0
      },
      "11_1":{  
         "type":"TILES2",
         "rotation":0
      },
      "12_1":{  
         "type":"TILES2",
         "rotation":0
      },
      "13_1":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "14_1":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_2":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_2":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_2":{  
         "type":"TILES2",
         "rotation":0
      },
      "10_2":{  
         "type":"TILES2",
         "rotation":0
      },
      "11_2":{  
         "type":"TILES2",
         "rotation":0
      },
      "12_2":{  
         "type":"TILES2",
         "rotation":0
      },
      "13_2":{  
         "type":"GREYWALL2",
         "rotation":1,
         "object":"12_2"
      },
      "14_2":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_3":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_3":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_3":{  
         "type":"TILES2",
         "rotation":0
      },
      "10_3":{  
         "type":"TILES2",
         "rotation":0
      },
      "11_3":{  
         "type":"TILES2",
         "rotation":0
      },
      "12_3":{  
         "type":"TILES2",
         "rotation":0
      },
      "13_3":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "14_3":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_4":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_4":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_4":{  
         "type":"TILES2",
         "rotation":0
      },
      "10_4":{  
         "type":"TILES2",
         "rotation":0
      },
      "11_4":{  
         "type":"TILES2",
         "rotation":0
      },
      "12_4":{  
         "type":"TILES2",
         "rotation":0
      },
      "13_4":{  
         "type":"GREYWALL2",
         "rotation":1,
         "object":"12_4"
      },
      "14_4":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_5":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_5":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_5":{  
         "type":"WOOD",
         "rotation":0
      },
      "10_5":{  
         "type":"WOOD",
         "rotation":0
      },
      "11_5":{  
         "type":"WOOD",
         "rotation":0
      },
      "12_5":{  
         "type":"WOOD",
         "rotation":0
      },
      "13_5":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "14_5":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_6":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_6":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_6":{  
         "type":"WOOD",
         "rotation":0
      },
      "10_6":{  
         "type":"WOOD",
         "rotation":0
      },
      "11_6":{  
         "type":"WOOD",
         "rotation":0
      },
      "12_6":{  
         "type":"WOOD",
         "rotation":0
      },
      "13_6":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "14_6":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_7":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_7":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_7":{  
         "type":"WOOD",
         "rotation":0
      },
      "10_7":{  
         "type":"WOOD",
         "rotation":0
      },
      "11_7":{  
         "type":"WOOD",
         "rotation":0
      },
      "12_7":{  
         "type":"WOOD",
         "rotation":0
      },
      "13_7":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "14_7":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_8":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_8":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_8":{  
         "type":"WOOD",
         "rotation":0
      },
      "10_8":{  
         "type":"WOOD",
         "rotation":0
      },
      "11_8":{  
         "type":"WOOD",
         "rotation":0
      },
      "12_8":{  
         "type":"WOOD",
         "rotation":0
      },
      "13_8":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "14_8":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_7":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_9":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "9_9":{  
         "type":"WOOD",
         "rotation":0
      },
      "10_9":{  
         "type":"WOOD",
         "rotation":0
      },
      "11_9":{  
         "type":"WOOD",
         "rotation":0
      },
      "12_9":{  
         "type":"WOOD",
         "rotation":0
      },
      "13_9":{  
         "type":"GREYWALL2",
         "rotation":1
      },
      "8_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "9_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "10_10":{  
         "type":"FLOOR",
         "rotation":0
      },
      "11_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "12_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "13_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "8_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "9_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "10_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "11_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "12_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "13_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_7":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_8":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_8":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_9":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_9":{  
         "type":"FLOOR",
         "rotation":0
      },
      "14_9":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_9":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "7_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "14_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "15_10":{  
         "type":"GREYWALL2",
         "rotation":0
      },
      "6_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "14_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_11":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_0":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_1":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_2":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_3":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_4":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_5":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_6":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_0":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_1":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_2":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_3":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_4":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_5":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_6":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "9_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "10_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "11_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "12_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "13_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "14_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_12":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "7_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "8_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "9_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "10_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "11_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "12_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "13_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "14_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "15_13":{  
         "type":"FLOOR",
         "rotation":0
      },
      "6_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "7_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "8_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "9_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "10_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "11_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "12_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "13_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "14_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "15_14":{  
         "type":"ROAD",
         "rotation":0
      },
      "6_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "7_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "8_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "9_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "10_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "11_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "12_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "13_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "14_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "15_15":{  
         "type":"ROAD",
         "rotation":0
      },
      "6_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "7_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "8_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "9_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "10_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "11_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "12_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "13_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "14_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "15_16":{  
         "type":"ROAD",
         "rotation":0
      },
      "6_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "7_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "8_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "9_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "10_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "11_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "12_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "13_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "14_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "15_17":{  
         "type":"ROAD",
         "rotation":0
      },
      "6_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "7_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "8_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "9_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "10_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "11_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "12_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "13_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "14_18":{  
         "type":"ROAD",
         "rotation":0
      },
      "15_18":{  
         "type":"ROAD",
         "rotation":0
      }
   },
   "object":{  
      "12_2":{  
         "type":"FRIDGE",
         "block":{  
            "x":12,
            "y":2
         },
         "rotation":3
      },
      "10_1":{  
         "type":"TABLE3",
         "block":{  
            "x":10,
            "y":1
         },
         "rotation":3
      },
      "10_2":{  
         "type":"TABLE3",
         "block":{  
            "x":10,
            "y":2
         },
         "rotation":3
      },
      "10_3":{  
         "type":"TABLE3",
         "block":{  
            "x":10,
            "y":3
         },
         "rotation":3
      },
      "9_4":{  
         "type":"OVEN",
         "block":{  
            "x":9,
            "y":4
         },
         "rotation":2
      },
      "12_4":{  
         "type":"FRIDGE",
         "block":{  
            "x":12,
            "y":4
         },
         "rotation":3
      },
      "11_5":{  
         "type":"TABLE4",
         "block":{  
            "x":11,
            "y":5
         },
         "rotation":2
      },
      "10_5":{  
         "type":"TABLE4",
         "block":{  
            "x":10,
            "y":5
         },
         "rotation":2
      },
      "12_5":{  
         "type":"DRAWERS",
         "block":{  
            "x":12,
            "y":5
         },
         "rotation":0
      },
      "12_8":{  
         "type":"CHAIR2",
         "block":{  
            "x":12,
            "y":8
         },
         "rotation":0
      },
      "11_8":{  
         "type":"CHAIR2",
         "block":{  
            "x":11,
            "y":8
         },
         "rotation":0
      },
      "11_9":{  
         "type":"TABLE5",
         "block":{  
            "x":11,
            "y":9
         },
         "rotation":0
      },
      "12_9":{  
         "type":"TABLE5",
         "block":{  
            "x":12,
            "y":9
         },
         "rotation":0
      },
      "9_7":{  
         "type":"CHAIR2",
         "block":{  
            "x":9,
            "y":7
         },
         "rotation":1
      },
      "9_8":{  
         "type":"CHAIR2",
         "block":{  
            "x":9,
            "y":8
         },
         "rotation":1
      },
      "9_9":{  
         "type":"CHAIR2",
         "block":{  
            "x":9,
            "y":9
         },
         "rotation":1
      }
   },
   "character":{  

   }
}